# Generated by Django 3.1.4 on 2021-02-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('numerotelefonico', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('edad', models.IntegerField()),
                ('estadocliente', models.BooleanField()),
                ('calle', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('codigopostal', models.CharField(max_length=7)),
                ('pais', models.CharField(max_length=7)),
                ('informacion', models.CharField(max_length=7)),
            ],
        ),
    ]
